

export const FETCH_COURSES_RQUEST = 'FETCH_COURSES_RQUEST';
export const FETCH_COURSES_SUCCESS = 'FETCH_COURSES_SUCCESS';

export const CREATE_COURSE_RQUEST = 'CREATE_COURSE_RQUEST';
export const CREATE_COURSE_SUCCESS = 'CREATE_COURSE_SUCCESS';

export const UPDATE_COURSE_REQUEST = 'UPDATE_COURSE_REQUEST';
export const UPDATE_COURSE_SUCCESS = 'UPDATE_COURSE_SUCCESS';

export const DELETE_COURSE_REQUEST = 'DELETE_COURSE_REQUEST';
export const DELETE_COURSE_SUCCESS = 'DELETE_COURSE_SUCCESS';

export const FETCH_COURSE_FAILURE = 'FETCH_COURSE_FAILURE';


